controllers/TaskController.php
<?php

namespace app\controllers;

use app\models\tasks_comment\TasksComment;
use app\models\tasks_image\TasksImage;
use app\models\task\Task;
use app\models\upload\UploadImageForm;
use app\models\user\User;
use Yii;
use yii\caching\DbDependency;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\UploadedFile;

class TaskController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['index', 'view', 'upload-image', 'add-comment'],
                'rules' => [
                    [
                        'actions' => [
                            'index', 'view', 'upload-image', 'add-comment'
                        ],
                        'allow' => true,
                        'roles' => ['admin', 'boss', 'manager', 'tleader', 'user'],
                    ],
                    [
                        'actions' => [
                            'index', 'view', 'upload-image', 'add-comment'
                        ],
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Displays calendar list of user`s tasks.
     *
     * @return string
     */
    public function actionIndex()
    {
        // Get current ID of logined user
        $userId = Yii::$app->user->getId() ?: '1000';
        $dependency = new DbDependency();
        $dependency->sql = 'SELECT MAX([[updated_at]]) FROM {{task}}';
        $duration = 3600 * 24 * 1;

        $cache = Yii::$app->cache;
        $key = 'calendar_' . $userId;

        if (!$calender = $cache->get($key)) {
            // Fill array keyes with [1, .., date("t")].
            // date("t") - count of days in current month
            $calendar = array_fill_keys(range(1, date("t")), []);

            foreach (Task::getByCurrentMonth($userId) as $task) {
                // Get current $task->date and create new DateTime object
                // $date->format("j") -- Day of the month: 1, 2, .., 31
                // Fill array $calender with $task objects
                $date = \DateTime::createFromFormat("Y-m-d H:i:s", $task->deadline);
                $calendar[$date->format("j")][] = $task;
            }

            $cache->set($key, $calendar, $duration, $dependency);
        } else {
            $calendar = $cache->get($key);
        }

        return $this->render('index', ['calendar' => $calendar]);
    }

    /**
     * Displays a single Task model.
     *
     * @param integer $id - ID
     *
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $message = '';

        return $this->render(
            'view',
            [
                'model' => $this->findModel($id),
                'message' => $message,
            ]
        );
    }

    /**
     * Function for upload image
     *
     * @return boolean|string
     */
    public function actionUploadImage()
    {
        $modelImageFile = new UploadImageForm();
        $modelDBImage = new TasksImage();
        $modelDBImage->task_id = Yii::$app->request->get('task_id');

        if (Yii::$app->request->isPost) {
            $modelImageFile->imageFile
            = UploadedFile::getInstance($modelImageFile, 'imageFile');

            if ($modelImageFile->upload()) {
                $modelDBImage->name = $modelImageFile->newImageName;
                $modelDBImage->save();

                $message = 'Image successfully uploaded';

                return $this->redirect(
                    [
                        'view',
                        'id' => $modelDBImage->task_id,
                        'message' => $message,
                    ]
                );
            }
        }

        return $this->render('upload-image', ['model' => $modelImageFile]);
    }

    /**
     * Function for upload image
     *
     * @return boolean|string
     */
    public function actionAddComment()
    {
        $model = new TasksComment();
        $model->task_id = Yii::$app->request->get('task_id');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->task_id]);
        }

        return $this->render('add-comment', ['model' => $model]);
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id - ID
     *
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/task/_comment_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $modelComment app\models\tasks_comment\TasksComment */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="row">
    <div class="col-lg-9">
    <p>For comment fill out the following field:</p>
<div class="tasks_comment-form">

    <?php $form = ActiveForm::begin([
    'id' => 'comment-form',
    'fieldConfig' => [
        'template' => "<div>{label}</div><br><div class=\"col-lg-9\">{input}</div><br><div class=\"col-lg-9\">{error}</div><br>",
        'labelOptions' => ['class' => 'col-lg-2 control-label'],
    ],
]);?>

    <?=$form->field($model, 'body')->textarea(['autofocus' => true, 'rows' => 8]);?>

    <div class="form-group">
    <br><br>
        <?=Html::submitButton(
    'Submit',
    [
        'class' => 'btn btn-primary',
        'name' => 'comment-button',
    ]
);?>

    </div>

    <?php ActiveForm::end();?>

</div>
</div>
</div>

views/task/_image_form.php
<?php

/* @var $this yii\web\View */
/* @var $modelComment app\models\tasks_image\TasksImage */
/* @var $form yii\widgets\ActiveForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>
<div class="row">
    <div class="col-lg-8">
        <p>For uploading image</p>
        <div class="tasks-image-form">

        <?php $form = ActiveForm::begin(
    [
        'id' => 'image-form',
        'fieldConfig' => [
            'template' => "{label}\n
            <div class=\"col-lg-3\">{input}</div>\n
            <div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]
);
?>

    <?=$form->field($modelImageFile, 'imageFile')->fileInput();?>

    <div class="form-group">

    <?=Html::submitButton(
    'Upload image',
    [
        'class' => 'btn btn-primary',
        'name' => 'image-button',
    ]
);
?>

    </div>

    <?php ActiveForm::end();?>

        </div>
    </div>
</div>

views/task/add-comment.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\tables\Task */

$this->title = 'Add comment to task';
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['task']];
$this->params['breadcrumbs'][] = ['label' => 'Task',
    'url' => ['view', 'id' => $model->task_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tasks-comment">

    <h1><?=Html::encode($this->title);?></h1>

    <?=$this->render('_comment_form',
    [
        'model' => $model,
    ]);?>

</div>

views/task/create.php
<?php
/** @var \app\models\tables\Task $model */
use \yii\helpers\Html;
use \yii\widgets\ActiveForm;

/*echo \yii\jui\DatePicker::widget([
'name' => 'my-date'
'model' => $model,
'attribute' => 'date'
]);
 */
$form = ActiveForm::begin([
    'id' => 'create_task',
    'options' => [
        'class' => 'form-vertical',
    ],
]);

echo $form->field($model, 'name')->textInput();
echo $form->field($model, 'date')->widget(\yii\jui\DatePicker::class, []);
echo $form->field($model, 'description')->textarea();
echo $form->field($model, 'user_id')->textInput();

echo Html::submitButton("Создать", ['class' => 'btn btn-success']);
ActiveForm::end();

views/task/index.php
<?php
/** @var array $calendar */
use Yii;
use yii\helpers\Html;
use yii\helpers\Url;

?>
<div>
<?=Yii::t('app/task', 'Current date: {0, date, dd MMMM yyyy}', time());?>
</div>
<table class="table table-bordered">
    <tr>
        <td>
        <?=Yii::t('app/task', 'Date of month');?>
        </td>
        <td><?=Yii::t('app/task', 'Event');?></td>
        <td><?=Yii::t('app/task', 'Done');?></td>
        <td><?=Yii::t('app/task', 'Total events');?></td>
    </tr>
    <?php foreach ($calendar as $day => $events) : ?>
        <tr>
            <td class="td-date"><span class="label label-success"><?=$day;?></span></td>
            <td>
                <?= (count($events) > 0) ?
                '<p>' . ucfirst($events[0]->name) . '</p><p class="small">' .
                ucfirst($events[0]->description) . '</p>'
                : '-';
                ?>
            </td>
            <td>
            <?=(count($events) > 0) ?
            '<p>' . Yii::$app->formatter->asBoolean($events[0]->done) : '-' . '</p>';
            ?>
            </td>
            <td class="td-event">
                <?= (count($events) > 0) ? Html::a(
                    count($events),
                    Url::to(['task/view', 'id' => $events[0]->id])
                ) : '-';
                ?>
            </td>
        </tr>
    <?php endforeach;?>
</table>

views/task/upload-image.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$form = ActiveForm::begin(
    [
        'options' => ['enctype' => 'multipart/form-data'],
    ]
);

echo $form
    ->field($model, 'imageFile')
    ->fileInput(['accept' => 'image/*']);

echo Html::submitButton(
    'Upload Image',
    [
        'class' => "btn btn-lg btn-primary",
        'name' => 'upload-button',
    ]
);

ActiveForm::end();

views/task/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\tables\Task */

$this->title = $model->name;
$this->params['breadcrumbs'][]
    = ['label' => Yii::t('app/task', 'Tasks'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-view">

    <h1><?=Html::encode($this->title)?></h1>

    <?=DetailView::widget([
    'model' => $model,
    'attributes' => [
        'id',
        'name',
        'deadline',
        'description:html',
        'user_id',
    ],
]);?>
</div>

<div class="row">
    <div class="col-lg-8">

        <button class="btn btn-lg btn-primary">

        <?=Html::a(
            Yii::t('app/task', 'Add comment'),
            Url::to(['@web/task/add-comment', 'task_id' => $model->id], true),
            ['class' => 'link-white']
        );?>

        </button>

        <button class="btn btn-lg btn-primary">

        <?=Html::a(
            Yii::t('app/task', 'Upload image'),
            Url::to(['@web/task/upload-image', 'task_id' => $model->id], true),
            ['class' => 'link-white']
        );?>

        </button>
    </div>
    <?php $message = Yii::$app->request->get('message');?>
    <p><?php print $message ?: '';?></p>
</div>